const projects = [
    {
        id: '1',
        title: 'THESIS',
        description: "The multimedia installation blended environmental art with sociopolitical commentary, exploring themes of collective memory and modern Greek identity through abstract expressionism in space. Sculptural elements appeared to merge with or emerge from the walls, creating a fluid, immersive environment. A central column was transformed into a carousel displaying artworks in each direction, symbolizing identity's layered nature. Embedded within this dynamic space were two art video games, 57 and LEVEL ZERO, whose pixel art aesthetics critically engaged with the medium’s evolution. This integration of tactile and digital elements bridged contemporary art and game design, offering a multifaceted experience.",
        category: "art",
        images: [
          './images/THESIS/1_thesis.JPG',
          './images/THESIS/thesis-image-0.jpg',
          './images/THESIS/thesis-image-1.jpg',
          './images/THESIS/thesis-image-2.jpg',
          './images/THESIS/thesis-image-3.jpg',
          './images/THESIS/thesis-image-4.jpg',
          './images/THESIS/thesis-image-5.jpg',
          './images/THESIS/thesis-image-6.jpg',
          './images/THESIS/thesis-image-7.jpg',
          './images/THESIS/thesis-image-8.jpg',
          './images/THESIS/thesis-image-9.jpg',
          './images/THESIS/thesis-image-10.jpg',
          './images/THESIS/thesis-image-11.jpg',
          './images/THESIS/thesis-image-12.jpg',
          './images/THESIS/thesis-image-13.jpg',
          './images/THESIS/thesis-image-14.jpg',
          './images/THESIS/thesis-image-15.jpg',
          './images/THESIS/thesis-image-16.jpg',
          './images/THESIS/thesis-image-17.jpg',
          './images/THESIS/thesis-image-18.jpg',
          './images/THESIS/thesis-image-19.jpg',
          './images/THESIS/thesis-image-20.jpg',
          './images/THESIS/thesis-image-21.jpg',
          './images/THESIS/thesis-image-22.jpg',
          './images/THESIS/thesis-image-23.jpg',
          './images/THESIS/thesis-image-24.jpg',
          './images/THESIS/thesis-image-25.jpg',
          './images/THESIS/thesis-image-26.jpg',
          './images/THESIS/thesis-image-27.jpg',
          './images/THESIS/thesis-image-28.jpg',
          './images/THESIS/thesis-image-29.jpg',
          './images/THESIS/thesis-image-30.jpg',
          './images/THESIS/thesis-image-31.jpg',
          './images/THESIS/thesis-image-32.jpg',
          './images/THESIS/thesis-image-33.jpg',
          './images/THESIS/thesis-image-34.jpg',
          './images/THESIS/thesis-image-35.jpg',
          './images/THESIS/thesis-image-36.jpg',
          './images/THESIS/thesis-image-37.jpg',
          './images/THESIS/thesis-image-38.jpg',
          './images/THESIS/thesis-image-39.jpg',
          './images/THESIS/thesis-image-40.jpg',
          './images/THESIS/thesis-image-41.jpg',
          './images/THESIS/thesis-image-42.jpg',
          './images/THESIS/thesis-image-43.jpg',
          './images/THESIS/thesis-image-44.jpg'
        ],
      },
      {
        id: '2',
        title: 'ADAF',
        description: 'In May 2024, Maria Karra showcased the Myrtis project at the Athens Digital Arts Festival (ADAF), presenting a thought-provoking multimedia installation. The installation invited visitors into an immersive experience, guided by narrators using dual headsets to listen to the Myrtis e.p.. This innovative approach combined sound, storytelling, and visual elements, creating an intimate journey through the themes and historical resonance embodied in the project. .',
        category: "art",
        images: [
          './images/myrtis/myrtis-image-0.jpg',
          './images/myrtis/myrtis-image-1.jpeg',
          './images/myrtis/myrtis-image-2.jpeg',
          './images/myrtis/myrtis-image-3.jpeg',
          './images/myrtis/myrtis-image-4.jpg',
          './images/myrtis/myrtis-image-5.jpg',
          './images/myrtis/myrtis-image-6.jpg',
          './images/myrtis/myrtis-image-7.jpg',
          './images/myrtis/myrtis-image-8.jpg',
          './images/myrtis/myrtis-image-9.jpg',
          './images/myrtis/myrtis-image-10.jpg',
          './images/myrtis/myrtis-image-11.jpg',
          './images/myrtis/myrtis-image-12.jpg',
          './images/myrtis/myrtis-image-13.jpg',
          './images/myrtis/myrtis-image-14.jpeg',
          './images/myrtis/myrtis-image-15.jpeg',
          './images/myrtis/myrtis-image-16.jpeg',
          './images/myrtis/myrtis-image-17.jpeg',
          './images/myrtis/myrtis-image-18.jpeg',
          './images/myrtis/myrtis-image-19.jpeg',
        ],
      },
      {
        id: '3',
        title: 'DISTUPTION',
        description: '',
        category: "art",
        images: [
          './images/Disruption/3_disruption.jpeg',
          './images/Disruption/disruption-image-0.jpeg.png',
          './images/Disruption/disruption-image-1.jpeg.png',
          './images/Disruption/disruption-image-2.jpeg.png',
          './images/Disruption/disruption-image-3.jpeg.png',
          './images/Disruption/disruption-image-4.jpeg.png',
          './images/Disruption/disruption-image-5.jpeg.jpg',
          './images/Disruption/disruption-image-6.jpeg.png',
          './images/Disruption/disruption-image-7.jpeg.png',
          './images/Disruption/disruption-image-8.jpeg.png',
          './images/Disruption/disruption-image-9.jpeg.png',
        ],
      },
      {
        id: '4',
        title: 'MYRTIS',
        description: "The Myrtis project has been a pivotal part of my artistic evolution, merging history, contemporary art, music, and storytelling. Inspired by the reconstructed face of a 2,500-year-old Athenian girl, Myrtis, the project delves into themes of identity, resilience, and the connection between past and present. I contributed to the 2021 Triptych of Myrtis exhibition at the National War Museum in Athens, showcasing Myrtis as a symbol of cultural continuity. In collaboration with Christoforos Alamanis, I co-created the Myrtis EP, a six-song experimental electronic music project that narrates Myrtis' story. Currently, I am illustrating a fairytale inspired by Myrtis and working on concept sketches for a literary work by Dr. Peny Tsakanikou, a researcher in Palaeolithic archaeology. Looking ahead, I am collaborating with Manolis Papagrigorakis on the potential creation of a video game based on Myrtis' story, combining my love for game design with historical storytelling.",
        category: "art",
        images: [
          './images/3_Myrtis-Project/myrtis-image-0.jpeg.jpg',
          './images/3_Myrtis-Project/myrtis-image-0.jpeg16.png',
          './images/3_Myrtis-Project/myrtis-image-1.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-2.jpeg.jpg',
          './images/3_Myrtis-Project/myrtis-image-3.jpeg.jpg',
          './images/3_Myrtis-Project/myrtis-image-4.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-5.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-6.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-8.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-9.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-10.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-11.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-13.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-14.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-15.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-16.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-17.jpeg.png',
          './images/3_Myrtis-Project/myrtis-image-18.jpeg.png',
        ],
      },
      {
        id: '5',
        title: 'FAMILY SECRETS',
        description: '',
        category: "art",
        images: [
          './images/family-secrets/5_family-secrets.jpg',
          './images/family-secrets/family-secrets-image-0.jpeg.jpg',
          './images/family-secrets/family-secrets-image-1.jpeg.jpeg',
          './images/family-secrets/family-secrets-image-2.jpeg.jpeg',
          './images/family-secrets/family-secrets-image-4.jpeg.jpg',
        ],
      },
      {
        id: '6',
        title: 'IMPRINT-ED',
        description: '',
        category: "art",
        images: [
          './images/Polaroid-Imprint-ed/5_imprint-ed.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-0.jpeg.JPG',
          './images/Polaroid-Imprint-ed/polaroids-image-1.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-2.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-3.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-4.jpeg.JPG',
          './images/Polaroid-Imprint-ed/polaroids-image-5.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-6.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-7.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-8.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-9.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-10.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-11jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-12.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-13.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-14.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-15.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-16.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-17.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-18.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-19.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-20.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-21.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-22.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-23.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-24.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-25.jpeg.jpg',
          './images/Polaroid-Imprint-ed/polaroids-image-26.jpeg.jpg'
        ],
      },
      {
        id: '7',
        title: 'QUARANTINE REGISTRATION',
        description: '',
        category: "art",
        images: [
          './images/Quarantine-registration/quarantine-registration-image-0.jpeg.jpg',
          './images/Quarantine-registration/quarantine-registration-image-1.jpeg.jpg',
        ],
      },
      {
        id: '8',
        title: 'ERASMUS RESIDENCY',
        description: '',
        category: "art",
        images: [
          './images/Erasmus-Residency/erasmus-image-0.jpg',
          './images/Erasmus-Residency/family-secrets-image-1.jpg',
        ],
      },
      {
        id: '9',
        title: 'ZAGREB',
        description: '',
        category: "art",
        images: [
          './images/Zagreb/zagreb-image-0.jpg',
          './images/Zagreb/zagreb-image-1.jpg',
          './images/Zagreb/zagreb-image-2.jpg',
          './images/Zagreb/zagreb-image-3.jpg',
          './images/Zagreb/zagreb-image-4.jpg',
        ],
      },
      {
        id: '10',
        title: 'SKETCH IT',
        description: '',
        category: "art",
        images: [
          './images/Sketch-It/sketch-it-image-0.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-1.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-2.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-3.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-4.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-5.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-6.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-7.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-8.jpeg.jpg',
          './images/Sketch-It/sketch-it-image-9.jpeg.jpg',
        ],
      },
      {
        id: '11',
        title: '2020',
        description: '',
        category: "art",
        images: [
          './images/2020/2020-image-0.jpeg.jpg',
          './images/2020/2020-image-1.jpeg.jpg',
          './images/2020/2020-image-2.jpeg.jpg',
        ],
      },
      {
        id: '12',
        title: 'DROP',
        description: '',
        category: "art",
        images: [
          './images/Drop/drop-image-0.jpeg.jpg',
          './images/Drop/drop-image-1.jpeg.jpg',
          './images/Drop/drop-image-2.jpeg.jpg',
        ],
      },
      {
        id: '13',
        title: 'BASEMENT',
        description: '',
        category: "art",
        images: [
          './images/basement/12_Basement.jpg',
          './images/basement/drop-image-0.jpeg.jpg',
          './images/basement/drop-image-1.jpeg.jpg',
          './images/basement/drop-image-2.jpeg.jpg',
        ],
      },
      {
        id: '14',
        title: 'GAIA',
        description: '',
        category: "art",
        images: [
          './images/Gaia/13_Gaia.jpg',
          './images/Gaia/gaia-image-0.jpeg.jpg',
          './images/Gaia/gaia-image-1.jpeg.jpg',
        ],
      },
      {
        id: '15',
        title: 'INK IT',
        description: '',
        category: "art",
        images: [
          './images/Ink-it/14_Ink-It.jpg',
          './images/Ink-it/ink-it-image-0.jpeg.jpg',
          './images/Ink-it/ink-it-image-1.jpeg.jpg',
          './images/Ink-it/ink-it-image-2.jpeg.jpg',
          './images/Ink-it/ink-it-image-3.jpeg.jpg',
          './images/Ink-it/ink-it-image-4.jpeg.jpg',
          './images/Ink-it/ink-it-image-5.jpeg.jpg',
          './images/Ink-it/ink-it-image-6.jpeg.jpg',
          './images/Ink-it/ink-it-image-7.jpeg.jpg',
          './images/Ink-it/ink-it-image-8.jpeg.jpg',
        ],
      },
      {
        id: '16',
        title: 'LEVEL 0',
        description: `<iframe src="https://itch.io/embed/3227341" width="552" height="167" frameborder="0">
                <a href="https://svelto-hotza.itch.io/level-0">LEVEL 0 by svelto hotza</a>
            </iframe><br><br>LEVEL 0 is part of the multimedia installation You were playing. And while you were playing...you fell. The game delves into the theme of societal progress, using minimalist mechanics to explore the repetitive nature of struggles and the illusion of progress. Players navigate simple yet thought-provoking obstacles that reflect the cyclical challenges individuals face. The pixel art style evokes nostalgia while reinforcing the game's critique of systemic issues. Through its abstract gameplay, LEVEL 0 offers a powerful commentary on how societal patterns continuously shape our collective experience.`,
        category: "game-art",
        images: [
            './images/level_0/screen5.png',
            './images/level_0/thumb.png',
            './images/level_0/screen2.png'
        ]
      },
      {
        id: '17',
        title: '2D Platformer Project',
        description: `<iframe frameborder="0" src="https://itch.io/embed/2887182" width="552" height="167"><a href="https://karrma-222.itch.io/2d-platformer0">2D Platformer.0 by Karrma 222</a></iframe><br><br>This is my 2D Platformer experimental project.`,
        category: "game-art",
        images: [
            './images/2DPlatformer/game2_1.png',
            './images/2DPlatformer/game2_2.png',
            './images/2DPlatformer/game2_3.png'
        ]
      },
      {
        id: '18',
        title: '2D Shooter Project',
        description: `<iframe height="167" frameborder="0" src="https://itch.io/embed/2790870" width="552"><a href="https://karrma-222.itch.io/2d-shooter">2D Shooter by Karrma 222</a></iframe><br><br>This video game is considered to be a 2D Shooter Project.`,
        category: "game-art",
        images: [
            './images/2DShooter/game3_1.png',
            './images/2DShooter/game3_2.png',
            './images/2DShooter/game3_3.png',
        ]
      },
      {
        id: '19',
        title: 'Solar System Project',
        description: `<iframe src="https://itch.io/embed/2786115" width="552" height="167" frameborder="0"><a href="https://karrma-222.itch.io/solar-system-with-karrma-backround-music">Solar System with Karrma  backround music by Karrma 222</a></iframe><br><br>This is my solar system project. I added the following components:

        Mars
        Mercury
        Venuss
        Saturn
        Jupiter
        Uranus
        Neptune
        A Mini Camera that is following Earth
        Music that I published on spotify under the artistic name: Karrma, album: MYRTIS
        New  Tectures for Venus and the Sun`,
        category: "game-art",
        images: [
            './images/SolarSystem/solar1.png',
            './images/SolarSystem/solar2.png',
            './images/SolarSystem/solar3.png'
        ]
      },
      {
        id: '20',
        title: 'Experimental Board Game',
        description: '"Experimental Board Game" is an innovative project still in its early stages of development. Inspired by the principles of Arte Útil, the game aims to foster creativity, collaboration, and problem-solving within the city of Karlsruhe. Set in 2024, players explore an interactive, thermochromic game board, where the city layout is revealed as they engage with the environment. Through observational cards such as Exploration, Listening, and Read Graffiti, players uncover social, cultural, and environmental issues within the city. The game encourages players to apply creative solutions to problems linked to the 17 Sustainable Development Goals (SDGs). With components like "Paralogés" cards, structures, and blank cards, players are invited to think abstractly and contribute their own ideas. Currently in its first stages of creation, Experimental Board Game seeks to transform play into a meaningful social experience, where creativity and collective action drive the narrative.',
        category: "game-art",
        images: [
            './images/Experimental-Board-Game/experimental-board-game-image-0.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-1.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-2.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-3.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-4.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-5.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-6.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-7.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-8.jpeg.jpeg',
            './images/Experimental-Board-Game/experimental-board-game-image-9.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-10.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-11.jpeg.png',
            './images/Experimental-Board-Game/experimental-board-game-image-12.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-13.jpeg.jpg',
            './images/Experimental-Board-Game/experimental-board-game-image-14.jpeg.jpg',
        ]
      },
      {
        id: '21',
        title: 'Research of Trapped Vibes',
        description: 'The prototype of the art game Research of Trapped Vibes was developed during my Erasmus Studies Program at ESBAN in Nîmes, France, as part of a project that took place at the Le Vallon du Villaret artist residency. During this residency, I recorded a live performance, which served as the foundation for creating a short video game designed to complement the recording. Unfortunately, the project files were lost, and the game could not be completed.',
        category: "game-art",
        images: [
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-0.jpeg.PNG',
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-1.jpeg.PNG',
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-2.jpeg.PNG',
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-3.jpeg.PNG',
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-4.jpeg.PNG',
            './images/Research-of-Trapped-Vibes/screenshots/trapped-vibes-image-5.jpeg.PNG',
        ]
      }
];